import sqlite3 as sl

con = sl.connect('sdn.db')

sql = 'INSERT INTO tag (title) values(?)'

tagdata = [

('ABAP Connectivity',),
('ABAP Development',),
('ABAP Extensibility',),
('ABAP RESTful Application Programming Model',),
('ABAP Testing and Analysis',),
('Accessibility',),
('Advanced Financial Closing',),
('Aerospace and Defense',),
('Agentry',),
('Android',),
('API',),
('API Management',),
('APP PLATFORM Business Partner',),
('application function library SDK for SAP HANA',),
('Ariba Cloud Integration',),
('Ariba Network Integration for SAP Business Suite',),
('Artificial Intelligence',),
('Automotive',),
('Banking',),
('banking services from SAP',),
('Basis Technology',),
('Big Data',),
('Blockchain',),
('Business Entity Recognition',),
('business process transformation',),
('BW (SAP Business Warehouse)',),
('BW Analytic Engine (OLAP)',),
('BW Business Explorer (SAP BEx)',),
('BW Content and Extractors',),
('BW Data Modeling (WHM)',),
('BW Data Staging (WHM)',),
('BW Operational Data Provisioning (ODP)',),
('BW Planning',),
('BW SAP BEx Analyzer',),
('BW SAP BEx Web',),
('BW SAP HANA Data Warehousing',),
('BW SAP HANA Modeling Tools (Eclipse)',),
('C4C Analytics',),
('C4C Extensibility',),
('C4C Sales',),
('C4C Service',),
('Careers',),
('Certification',),
('Chemicals',),
('Cloud',),
('Cloud Connector',),
('Cloud Integration',),
('Cloud Operations',),
('Co-Innovation Lab',),
('connector for SAP Multi-Bank Connectivity',),
('Consumer Products',),
('Corporate Social Responsibility',),
('CRM Analytics',),
('CRM Billing',),
('CRM Interaction Center',),
('CRM Marketing',),
('CRM Master Data',),
('CRM Middleware',),
('CRM Mobile Sales and Service',),
('CRM Pricing and Configuration',),
('CRM Sales',),
('CRM Service',),
('CRM Web Channel',),
('CRM WebClient UI',),
('Customer Experience',),
('Customer Influence',),
('Customer Involvement',),
('Data and Analytics',),
('Data Attribute Recommendation',),
('Defense and Security',),
('Design Thinking',),
('Desktop Connection for SAP CRM',),
('development tools for SAP BTP, Neo environment',),
('DevOps',),
('Digital Technologies',),
('Digital Transformation',),
('Diversity and Inclusion',),
('Document Classification',),
('Document Information Extraction',),
('Duet Enterprise',),
('Earth Observation Analysis',),
('embedded launch activities',),
('Emotional Intelligence',),
('Employee Experience Management',),
('Engineering, Construction, and Operations',),
('Enterprise Services Repository for SAP NetWeaver Composition Environment',),
('EPM Add-In for Excel',),
('ERP ATP',),
('EWM - Basic Functions',),
('EWM - Basis',),
('EWM - Delivery Processing',),
('EWM - Goods Movement',),
('EWM - Interfaces',),
('EWM - Master Data',),
('EWM - Quality Management',),
('EWM - Radio Frequency',),
('EWM - Shipping and Receiving',),
('Extended Planning and Analysis',),
('field masking for SAP GUI',),
('field masking for SAPUI5 and SAP Fiori',),
('field masking for Web Client UI',),
('field masking for Web Dynpro for ABAP',),
('FIN (Finance)',),
('FIN Accounts Receivable and Payable',),
('FIN Asset Accounting',),
('FIN Cash Management',),
('FIN Controlling',),
('FIN Cost Object Controlling',),
('FIN General Ledger',),
('FIN Globalization Services',),
('FIN Material Ledger',),
('FIN Posting and Taxes',),
('FIN Product Cost Planning',),
('FIN Profitability Analysis',),
('FIN Real Estate',),
('FIN Travel Management',),
('FIN Treasury',),
('Focused Build for SAP Solution Manager',),
('Focused Insights for SAP Solution Manager',),
('Fundamental Library',),
('Future of Work',),
('FUZZY! DataCare Tools',),
('Global Trade Management',),
('Goods and Services Tax (GST India)',),
('Governance, Risk, Compliance (GRC), and Cybersecurity',),
('HCM (Human Capital Management)',),
('HCM Employee Self-Service',),
('HCM Fund/Position Management',),
('HCM Manager Self-Service',),
('HCM Payroll',),
('HCM Payroll Argentina',),
('HCM Payroll Brazil',),
('HCM Payroll Canada',),
('HCM Payroll Chile',),
('HCM Payroll Colombia',),
('HCM Payroll India',),
('HCM Payroll Mexico',),
('HCM Payroll Spain',),
('HCM Payroll USA',),
('HCM Pension Funds',),
('HCM Personnel Administration',),
('HCM Personnel Cost Planning',),
('HCM Personnel Development',),
('HCM Processes and Forms',),
('HCM Talent Management',),
('HCM Time Management',),
('Healthcare',),
('High Tech',),
('Higher Education and Research',),
('HP-UX',),
('HR renewal',),
('HTML5',),
('Hyperledger Fabric on SAP BTP',),
('IBM AIX',),
('IBM Db2 for i',),
('IBM Db2 for Linux, UNIX, and Windows',),
('IBM Db2 for z/OS',),
('IBM i',),
('IBM z/OS',),
('Identity Authentication',),
('Identity Provisioning',),
('Implementation Methodologies',),
('Industrial Manufacturing',),
('Industry Cloud',),
('Insurance',),
('Integration and Certification Center',),
('Intelligent Enterprise Institute',),
('Intelligent Scenario Lifecycle Management for SAP S/4HANA',),
('Internationalization and Unicode',),
('Internet of Things',),
('iOS',),
('IoT SIM management for SAP HANA',),
('Java',),
('JavaScript',),
('Kyma Open Source',),
('LE (Logistics Execution)',),
('LE Handling Unit Management',),
('LE Shipping',),
('LE Warehouse Management',),
('Life Sciences',),
('Linux on z',),
('localization as a self-service for SAP S/4HANA Cloud',),
('localization services',),
('logging of RFC and Web services',),
('logging of SAP BW access',),
('logging of SAP GUI for Windows',),
('logging of SAP GUI for Windows UI',),
('logging of Web Client UI',),
('logging of Web Dynpro for ABAP',),
('Machine Learning',),
('MAN (Manufacturing)',),
('MAN Batch Management',),
('MAN Material Requirements Planning',),
('MAN Production Planning (PP)',),
('Media',),
('Microsoft SQL Server',),
('Mill Products',),
('Mining',),
('MM (Materials Management)',),
('MM Inventory Management',),
('MM Invoice Verification',),
('MM Purchasing',),
('Mobile',),
('Mobile Application Integration Framework',),
('mobile development kit client',),
('MultiChain on SAP BTP',),
('Node.js',),
('NW ABAP Business Address Service',),
('NW ABAP Business Rule Framework (BRFplus)',),
('NW ABAP Communication Services',),
('NW ABAP Customizing Tools',),
('NW ABAP Data Archiving',),
('NW ABAP Gateway (OData)',),
('NW ABAP Integration Technology (ALE)',),
('NW ABAP Internet Communication Framework',),
('NW ABAP Monitoring Tools',),
('NW ABAP Print and Output Management',),
('NW ABAP Remote Function Call (RFC)',),
('NW ABAP Runtime Environment',),
('NW ABAP User Administration and Authorization',),
('NW ABAP User Authentication',),
('NW ABAP Web Services',),
('NW AS Java Administrator (NWA)',),
('NW Client/Server Technology (CST)',),
('NW Java Developer Studio (NWDS)',),
('NW Java Development Infrastructure (NWDI)',),
('NW Java Security and User Management',),
('NW Java Web Services',),
('NW TREX Search and Classification',),
('OData',),
('Oil, Gas, and Energy',),
('Open Connectors',),
('Open Source',),
('Oracle Database',),
('Oracle Linux',),
('Oracle Solaris',),
('Partnership',),
('Personalized Recommendation',),
('PLM (Product Lifecycle Management)',),
('PLM Classification',),
('PLM Document Management System (DMS)',),
('PLM Enterprise Asset Management (EAM)/Plant Maintenance (PM)',),
('PLM Project System (PS)',),
('PLM Quality Management (QM)',),
('PLM Variant Configuration',),
('PORTAL Administration and Development',),
('PORTAL Application Integration',),
('PORTAL Knowledge Management and Collaboration',),
('PORTAL Migration and Upgrade',),
('PORTAL Universal Worklist (UWL)',),
('PORTAL Visual Composer',),
('Price Calculation',),
('Professional Services',),
('Public Sector',),
('Python',),
('Qualtrics CoreXM',),
('Quorum on SAP BTP',),
('Red Hat Enterprise Linux',),
('Research and Development',),
('Retail',),
('RISE with SAP',),
('RISE with SAP for Automotive',),
('RISE with SAP for Consumer Products',),
('RISE with SAP for Industrial Machinery and Components',),
('RISE with SAP for Retail',),
('RISE with SAP for Utilities',),
('SAP .NET Connector (NCo)',),
('SAP 3D Visual Enterprise',),
('SAP 3D Visual Enterprise applications SDK',),
('SAP 3D Visual Enterprise Generator, OEM edition',),
('SAP 3D Visual Enterprise, third-party plug-ins',),
('SAP Access Control',),
('SAP Access Control for SAP S/4HANA',),
('SAP Access Violation Management by Pathlock',),
('SAP Activate',),
('SAP Adaptive Server Enterprise',),
('SAP Add-On Assembly Kit',),
('SAP address directories',),
('SAP Advanced Planning and Optimization',),
('SAP Advanced SQL Migration',),
('SAP Advantage Database Server',),
('SAP Afaria',),
('SAP Agent Connection',),
('SAP Agent Lifecycle Management',),
('SAP Agent Performance Management, enterprise edition',),
('SAP Agile Data Preparation',),
('SAP AI Business Services',),
('SAP AI Core',),
('SAP AI Launchpad',),
('SAP Alert Notification service for SAP BTP',),
('SAP Allocation and Rescheduling Optimization',),
('SAP Analysis for Microsoft Office',),
('SAP Analytics Cloud',),
('SAP Analytics Cloud for planning',),
('SAP Analytics Cloud, add-in for Microsoft Office',),
('SAP Analytics Cloud, analytics designer',),
('SAP Analytics Cloud, augmented analytics',),
('SAP Analytics Cloud, connectivity',),
('SAP Analytics Cloud, data modeling',),
('SAP Analytics Cloud, hybrid analytics',),
('SAP Analytics Hub',),
('SAP API Business Hub',),
('SAP Apparel and Footwear',),
('SAP AppGyver',),
('SAP Application Interface Framework',),
('SAP Archiving and Document Access by OpenText',),
('SAP Archiving and Document Access by OpenText for SAP S/4HANA',),
('SAP Archiving and Document Access by OpenText, cloud edition',),
('SAP Ariba Buying',),
('SAP Ariba Buying and Invoicing',),
('SAP Ariba Buying, partner edition',),
('SAP Ariba Catalog',),
('SAP Ariba Contract Invoicing',),
('SAP Ariba Contracts',),
('SAP Ariba Discount Management',),
('SAP Ariba Extensibility',),
('SAP Ariba Invoice Management',),
('SAP Ariba Live',),
('SAP Ariba open invoice conversion services add-on',),
('SAP Ariba Procurement',),
('SAP Ariba Procurement, cloud edition',),
('SAP Ariba Procurement, supplemental site add-on',),
('SAP Ariba Shopping',),
('SAP Ariba Sourcing',),
('SAP Ariba Sourcing, cloud edition',),
('SAP Ariba Spend Analysis',),
('SAP Ariba Supplier Lifecycle and Performance',),
('SAP Ariba Supplier Risk',),
('SAP ASE - BW Enablement',),
('SAP ASE - ERP Enablement',),
('SAP ASE - HADR Enablement',),
('SAP Asset Information Workbench by Utopia',),
('SAP Asset Performance Management',),
('SAP Asset Strategy and Performance Management',),
('SAP assurance and compliance software',),
('SAP assurance and compliance software for SAP S/4HANA',),
('SAP Audit Management',),
('SAP Authenticator',),
('SAP Auto-ID Infrastructure',),
('SAP Automation Pilot',),
('SAP Bank Communication Management',),
('SAP Batch Release Hub for Life Sciences',),
('SAP Big Data Services',),
('SAP Big Data Services tools',),
('SAP Billing and Revenue Innovation Management',),
('SAP Billing and Revenue Innovation Management, subscription order management',),
('SAP BTP SDK for Android',),
('SAP BTP SDK for iOS',),
('SAP BTP Security',),
('SAP BTP, ABAP environment',),
('SAP BTP, Cloud Foundry environment',),
('SAP BTP, Kyma runtime',),
('SAP BTP, serverless runtime',),
('SAP Budgeting and Planning for Public Sector',),
('SAP Build',),
('SAP Build Apps',),
('SAP Build Process Automation',),
('SAP Build Work Zone, advanced edition',),
('SAP Build Work Zone, standard edition',),
('SAP Business Application Studio',),
('SAP Business ByDesign',),
('SAP Business ByDesign Localization',),
('SAP Business Connector',),
('SAP Business Integrity Screening',),
('SAP Business Journeys',),
('SAP Business Network',),
('SAP Business Network Asset Collaboration',),
('SAP Business Network for Asset Management',),
('SAP Business Network for Logistics',),
('SAP Business Network for Procurement',),
('SAP Business Network Planning Collaboration',),
('SAP Business Network Supplier for Android',),
('SAP Business Network Supplier for iOS',),
('SAP Business Network Supply Chain Collaboration',),
('SAP Business One',),
('SAP Business One Cloud',),
('SAP Business One Extensibility',),
('SAP Business One, version for SAP HANA',),
('SAP Business Planning and Consolidation, version for SAP BW/4HANA',),
('SAP Business Planning and Consolidation, version for SAP NetWeaver',),
('SAP Business Planning and Consolidation, version for the Microsoft platform',),
('SAP Business Process Automation by Redwood',),
('SAP Business Process Management',),
('SAP Business Rules Management',),
('SAP Business Technology Platform',),
('SAP Business Technology Platform for Procurement',),
('SAP Business Warehouse Accelerator',),
('SAP Business Workflow',),
('SAP BusinessObjects - Authentication',),
('SAP BusinessObjects - BI Platform - SDK',),
('SAP BusinessObjects - Core Platform and Performance',),
('SAP BusinessObjects - OLAP',),
('SAP BusinessObjects - Platform Administration',),
('SAP BusinessObjects - Platform Infrastructure',),
('SAP BusinessObjects - Semantic Layer',),
('SAP BusinessObjects - Semantic Layer - SDK',),
('SAP BusinessObjects - Web Intelligence (WebI)',),
('SAP BusinessObjects - Web Intelligence - SDK',),
('SAP BusinessObjects BI support tool',),
('SAP BusinessObjects Business Intelligence platform',),
('SAP BusinessObjects BW Universe Builder',),
('SAP BusinessObjects Dashboards',),
('SAP BusinessObjects Design Studio',),
('SAP BusinessObjects Explorer',),
('SAP BusinessObjects Financial Consolidation',),
('SAP BusinessObjects geocoding',),
('SAP BusinessObjects Mobile',),
('SAP BW/4HANA',),
('SAP C/4HANA cockpit',),
('SAP Cash Application',),
('SAP Cell and Gene Therapy Orchestration',),
('SAP Central Business Configuration',),
('SAP Central Invoice Management',),
('SAP Central Process Scheduling by Redwood',),
('SAP Claims Management',),
('SAP Cloud ALM',),
('SAP Cloud Appliance Library',),
('SAP Cloud Application Programming Model',),
('SAP Cloud Applications Studio',),
('SAP Cloud for Customer add-ins',),
('SAP Cloud for Customer core applications',),
('SAP Cloud for Customer integration with SAP CRM',),
('SAP Cloud for Customer integration with SAP ERP',),
('SAP Cloud for Customer integration with SAP Marketing',),
('SAP Cloud for Customer integration with SAP S/4HANA',),
('SAP Cloud for Customer, server-side integration',),
('SAP Cloud for Real Estate, location management edition',),
('SAP Cloud Identity Access Governance',),
('SAP Cloud Integration for data services',),
('SAP Cloud Platform, industry edition, client libraries',),
('SAP Cloud Portal service',),
('SAP Cloud SDK',),
('SAP Cloud Transport Management',),
('SAP Code Vulnerability Analyzer',),
('SAP CodeJam',),
('SAP Collections and Disbursements for Insurance',),
('SAP Commerce',),
('SAP Commerce Cloud',),
('SAP Commercial Project Management',),
('SAP Commercial Project Management for SAP S/4HANA',),
('SAP Commissions',),
('SAP Community',),
('SAP Community Tutorial Exercises',),
('SAP Composition Environment',),
('SAP Concur',),
('SAP Condition Record Management by Vistex',),
('SAP Connected Health platform',),
('SAP Connectivity service',),
('SAP Contact Center',),
('SAP Content Agent service',),
('SAP Continuous Integration and Delivery',),
('SAP Contract Accounts Receivable and Payable',),
('SAP Convergent Charging',),
('SAP Convergent Invoicing',),
('SAP Convergent Mediation by DigitalRoute',),
('SAP Conversational AI',),
('SAP CoPilot',),
('SAP CPQ',),
('SAP CPQ, intelligent add-on',),
('SAP cProject Suite',),
('SAP Credential Store',),
('SAP CRM on-demand solution',),
('SAP CRM Sales integration with SAP CRM',),
('SAP CRM Sales integration with SAP ERP',),
('SAP CRM Service Manager',),
('SAP CRM, GWI client plug-in',),
('SAP Crystal Reports',),
('SAP Crystal Reports - SDK',),
('SAP Crystal Reports viewer',),
('SAP Crystal Reports, version for Eclipse',),
('SAP Crystal Reports, version for Visual Studio',),
('SAP Crystal Server',),
('SAP Customer Activity Repository',),
('SAP Customer Checkout',),
('SAP Customer Data Cloud',),
('SAP Customer Data Platform',),
('SAP Customer Engagement Center',),
('SAP Customer Experience Foundation',),
('SAP Customer Identity',),
('SAP Customer Loyalty',),
('SAP Customer Relationship Management',),
('SAP Data Federator',),
('SAP Data Insight',),
('SAP Data Integrator',),
('SAP Data Intelligence',),
('SAP Data Migration by Syniti',),
('SAP Data Quality Management',),
('SAP Data Quality Management for SAP NetWeaver MDM',),
('SAP Data Services',),
('SAP Data Visualization',),
('SAP Data Warehouse Cloud',),
('SAP Dealer Business Management',),
('SAP Decision Service Management',),
('SAP Demand Management',),
('SAP Demand Signal Management',),
('SAP Digital Content Processing by OpenText',),
('SAP Digital Content Processing by OpenText for SAP S/4HANA',),
('SAP Digital Manufacturing Cloud',),
('SAP Digital Manufacturing Insights',),
('SAP digital supplier network membership',),
('SAP digital supplier network membership for Supply Chain',),
('SAP Digital Vehicle Operations',),
('SAP Digital Vehicle Suite',),
('SAP Direct Store Delivery',),
('SAP Disclosure Management',),
('SAP Document Access by OpenText',),
('SAP Document and Reporting Compliance',),
('SAP Document Builder',),
('SAP Document Center',),
('SAP Document Management service',),
('SAP Document Presentment by OpenText',),
('SAP Document Presentment by OpenText for SAP S/4HANA',),
('SAP Document Presentment by OpenText for SAP S/4HANA, add-on for business correspondence',),
('SAP Dynamic Authorization Management by NextLabs, advanced edition',),
('SAP Dynamic Pricing by GK',),
('SAP Dynamic Pricing by GK, cloud edition',),
('SAP E-Recruiting',),
('SAP EAM Work Order',),
('SAP EarlyWatch Alert',),
('SAP Easy Document Management',),
('SAP Edge Services',),
('SAP EHS Safety Issue',),
('SAP Electronic Invoicing for Brazil (SAP Nota Fiscal Eletronica)',),
('SAP Electronic Invoicing for Brazil (SAP Nota Fiscal Eletronica) for SAP S/4HANA',),
('SAP Emarsys API',),
('SAP Emarsys Commerce Cloud Integration',),
('SAP Emarsys Customer Engagement',),
('SAP Emarsys Deliverability',),
('SAP Emarsys Loyalty',),
('SAP Emarsys Scripting Language',),
('SAP Emarsys Tactics',),
('SAP Emarsys web personalization',),
('SAP Enable Now',),
('SAP Enable Now, author option',),
('SAP Enable Now, cloud edition',),
('SAP Engineering Control Center',),
('SAP Engineering Control Center for SAP S/4HANA',),
('SAP Enhanced Maintenance and Service Planning',),
('SAP enhancement package for SAP CRM',),
('SAP enhancement package for SAP ERP',),
('SAP enhancement package for SAP ERP, version for SAP HANA',),
('SAP enhancement package for SAP Supplier Relationship Management',),
('SAP enhancement package for SAP Supply Chain Management',),
('SAP Enterprise Architecture Designer',),
('SAP Enterprise Architecture Designer, cloud edition',),
('SAP Enterprise Chatbot',),
('SAP Enterprise Contract Assembly',),
('SAP Enterprise Inventory and Service-Level Optimization',),
('SAP Enterprise Learning',),
('SAP Enterprise Portal',),
('SAP Enterprise Portal, enterprise workspaces',),
('SAP Enterprise Product Development',),
('SAP Enterprise Product Engineering',),
('SAP Enterprise Project Connection',),
('SAP Enterprise Store',),
('SAP Enterprise Threat Detection',),
('SAP Entitlement Management',),
('SAP Environment, Health, and Safety Management',),
('SAP EPM Unwired',),
('SAP ERP',),
('SAP ERP add-on for financial accounting and operations',),
('SAP ERP add-on for retail',),
('SAP ERP Central Component',),
('SAP ERP for Business All-in-One, manufacturing edition',),
('SAP ERP integration with SAP Concur solutions',),
('SAP ERP Order Status',),
('SAP ERP, add-on for embedded production planning and detailed scheduling',),
('SAP ERP, add-on for mobile integration',),
('SAP ERP, add-on for SAP PLM',),
('SAP ERP, enterprise services bundle',),
('SAP ERP, supply chain integration add-on for SAP Integrated Business Planning',),
('SAP Event Management',),
('SAP Event Mesh',),
('SAP Event Stream Processor',),
('SAP Exchange Infrastructure',),
('SAP Extended Diagnostics by CA',),
('SAP Extended Diagnostics by CA Wily',),
('SAP Extended ECM by OpenText, cloud add-on for capital projects and operations',),
('SAP Extended Enterprise Content Management by OpenText',),
('SAP Extended Enterprise Content Management by OpenText for SAP S/4HANA',),
('SAP Extended Enterprise Content Management by OpenText, add-on for Microsoft Office 365',),
('SAP Extended Enterprise Content Management by OpenText, cloud edition',),
('SAP Extended Warehouse Management',),
('SAP Fashion Management',),
('SAP Field Service',),
('SAP Field Service Management',),
('SAP Field Service Management for Windows Mobile',),
('SAP Field Service Management mobile app',),
('SAP Field Service Management, connector for SAP Business One',),
('SAP Field Service Management, connector for SAP ERP',),
('SAP Fieldglass Vendor Management System',),
('SAP File Lifecycle Management, localization for India',),
('SAP Financial Closing cockpit',),
('SAP Financial Information Management',),
('SAP Financial Services Data Management',),
('SAP Financial Statement Insights',),
('SAP Financial Supply Chain Management',),
('SAP Fiori',),
('SAP Fiori Client',),
('SAP Fiori Cloud',),
('SAP Fiori Elements',),
('SAP Fiori for request approvals',),
('SAP Fiori for SAP CRM',),
('SAP Fiori for SAP ERP',),
('SAP Fiori for SAP ERP HCM',),
('SAP Fiori for SAP S/4HANA',),
('SAP Fiori for SAP Student Lifecycle Management, admissions portal',),
('SAP Fiori front-end server',),
('SAP Fiori Launchpad',),
('SAP Fiori Makers',),
('SAP Fiori tools',),
('SAP Flexible Solution Billing',),
('SAP Focused Run',),
('SAP Folders Management',),
('SAP for Me',),
('SAP Forecasting and Replenishment',),
('SAP Forms service by Adobe',),
('SAP Fortify by Micro Focus',),
('SAP Funding Management',),
('SAP Gateway',),
('SAP General Ledger Migration',),
('SAP Geographical Enablement Framework',),
('SAP Global Batch Traceability',),
('SAP Global Track and Trace',),
('SAP Global Trade Services',),
('SAP Graph',),
('SAP GRC Access Approver',),
('SAP GRC Access Enforcer for SAP NetWeaver',),
('SAP GRC Compliance Calibrator for SAP NetWeaver',),
('SAP GRC Firefighter for SAP NetWeaver',),
('SAP GRC Policy Survey',),
('SAP GRC Role Expert for SAP NetWeaver',),
('SAP Group Reporting Data Collection',),
('SAP Guided Buying for SAP S/4HANA',),
('SAP HANA',),
('SAP HANA accelerator for SAP ASE',),
('SAP HANA Cloud',),
('SAP HANA Cloud, data lake',),
('SAP HANA Cloud, SAP Adaptive Server Enterprise',),
('SAP HANA Cloud, SAP Adaptive Server Enterprise replication',),
('SAP HANA Cloud, SAP HANA database',),
('SAP HANA dynamic tiering',),
('SAP HANA Enterprise Cloud',),
('SAP HANA Graph',),
('SAP HANA Info Access',),
('SAP HANA Live',),
('SAP HANA multi-model processing',),
('SAP HANA rules framework',),
('SAP HANA service for SAP BTP',),
('SAP HANA smart data integration',),
('SAP HANA Spatial',),
('SAP HANA streaming analytics',),
('SAP HANA studio',),
('SAP HANA, express edition',),
('SAP HANA, platform edition',),
('SAP Health',),
('SAP Help Portal',),
('SAP HR Approvals',),
('SAP Hybris as a Service',),
('SAP Identity Management',),
('SAP Industry Process Framework',),
('SAP InfoMaker',),
('SAP Information Lifecycle Management',),
('SAP Information Steward',),
('SAP InnoJam',),
('SAP Innovation Management',),
('SAP Inside Track',),
('SAP Integrated Business Planning for demand',),
('SAP Integrated Business Planning for demand-driven replenishment',),
('SAP Integrated Business Planning for inventory',),
('SAP Integrated Business Planning for response and supply',),
('SAP Integrated Business Planning for sales and operations',),
('SAP Integrated Business Planning for Supply Chain',),
('SAP Integration Strategy',),
('SAP Integration Suite',),
('SAP Integration Suite, managed gateway',),
('SAP Intelligent Clinical Supply Management',),
('SAP Intelligent Product Design',),
('SAP Intelligent Robotic Process Automation',),
('SAP Intelligent Sales Execution',),
('SAP Interactive Forms by Adobe',),
('SAP Intercompany Data Exchange',),
('SAP Internet of Things',),
('SAP Inventory Manager',),
('SAP Invoice and Goods Receipt Reconciliation',),
('SAP Invoice Management by OpenText',),
('SAP Invoice Management by OpenText for SAP S/4HANA',),
('SAP IQ',),
('SAP IT Infrastructure Management',),
('SAP IT Operations Analytics',),
('SAP Jam',),
('SAP Jam Collaboration',),
('SAP Jam Communities',),
('SAP Jam integration with SAP CRM',),
('SAP Java Connector (JCo)',),
('SAP Java Virtual Machine',),
('SAP Joint Venture Accounting',),
('SAP Knowledge Warehouse',),
('SAP Landscape Management',),
('SAP Landscape Management Cloud',),
('SAP Landscape Management, enterprise edition',),
('SAP Landscape Transformation',),
('SAP Landscape Transformation replication server',),
('SAP Learning Solution',),
('SAP Lease Administration by Nakisa',),
('SAP Leave Request',),
('SAP Liquidity Risk Management',),
('SAP Live Link 365',),
('SAP LoadRunner by Micro Focus',),
('SAP Loyalty Marketing',),
('SAP Lumira',),
('SAP Lumira, desktop edition',),
('SAP Lumira, server edition',),
('SAP Lumira, server version for SAP HANA',),
('SAP Lumira, server version for teams',),
('SAP Maintenance Assistant',),
('SAP Manufacturing Execution',),
('SAP Manufacturing Integration and Intelligence',),
('SAP Marketing',),
('SAP Marketing Cloud',),
('SAP Master Data Governance',),
('SAP MaxDB',),
('SAP Meat and Fish Management by msg for SAP S/4HANA',),
('SAP Mentors',),
('SAP Metadata Management',),
('SAP Meter Data Management by Siemens',),
('SAP Mobile App Framework',),
('SAP Mobile Asset Management',),
('SAP Mobile Cards',),
('SAP Mobile Documents',),
('SAP Mobile Platform',),
('SAP Mobile Platform SDK',),
('SAP Mobile Secure',),
('SAP Mobile Services',),
('SAP Mobile Start',),
('SAP Multi-Bank Connectivity',),
('SAP Multichannel Foundation for Utilities and Public Sector',),
('SAP Multiresource Scheduling',),
('SAP NetWeaver',),
('SAP NetWeaver Application Server',),
('SAP NetWeaver Application Server for ABAP',),
('SAP NetWeaver Application Server for ABAP for SAP Business Suite',),
('SAP NetWeaver Application Server for ABAP for SAP S/4HANA Cloud',),
('SAP NetWeaver Application Server for Java',),
('SAP NetWeaver Application Server for SAP S/4HANA',),
('SAP NetWeaver Enterprise Search',),
('SAP NetWeaver for Java, support tool',),
('SAP NetWeaver Master Data Management',),
('SAP NetWeaver Process Integration, adapters',),
('SAP NOW',),
('SAP Operational Process Intelligence',),
('SAP Order Management foundation',),
('SAP Organizational Visualization by Nakisa',),
('SAP Overall Equipment Effectiveness Management',),
('SAP Patient Management',),
('SAP Payment Approvals',),
('SAP Payment Engine',),
('SAP Payroll and Time Change Management',),
('SAP People Connect 365',),
('SAP Plant Connectivity',),
('SAP PLM interface',),
('SAP Point-of-Sale',),
('SAP Policy Management',),
('SAP Portfolio and Project Management',),
('SAP Portfolio and Project Management for SAP S/4HANA',),
('SAP PowerBuilder',),
('SAP PowerDesigner',),
('SAP Predictive Analytics',),
('SAP Predictive Analytics integrator',),
('SAP Predictive Asset Insights',),
('SAP Predictive Engineering Insights',),
('SAP Predictive Maintenance and Service, add-on for utilities',),
('SAP Predictive Maintenance and Service, on-premise edition',),
('SAP Predictive service',),
('SAP Pricing and Costing for Utilities',),
('SAP Process Control',),
('SAP Process Control for SAP S/4HANA',),
('SAP Process Integration',),
('SAP Process Integration, business-to-business add-on',),
('SAP Process Integration, connectivity add-on',),
('SAP Process Integration, secure connectivity add-on',),
('SAP Process Orchestration',),
('SAP Product and Quotation Management for Insurance',),
('SAP Product and REACH Compliance',),
('SAP Product Lifecycle Costing',),
('SAP Product Lifecycle Costing, cloud edition',),
('SAP Product Safety',),
('SAP Product Sourcing',),
('SAP Product, Quotation, and Underwriting Management',),
('SAP Production and Revenue Accounting',),
('SAP Productivity Pak by ANCILE',),
('SAP Profitability and Cost Management',),
('SAP Profitability and Performance Management',),
('SAP Public Sector Collection and Disbursement',),
('SAP Quality Center by Micro Focus',),
('SAP Quality Issue Management',),
('SAP Quality Issue Resolution',),
('SAP R/3',),
('SAP Rapid Marts',),
('SAP Readiness Check',),
('SAP Real Estate Management',),
('SAP RealSpend',),
('SAP Receivables Manager',),
('SAP Recipe Development',),
('SAP Replication Server',),
('SAP Resource and Portfolio Management',),
('SAP Retail Execution',),
('SAP Returns Authorization',),
('SAP Revenue Accounting and Reporting',),
('SAP Revenue Growth Optimization',),
('SAP Risk Management',),
('SAP Risk Management for SAP S/4HANA',),
('SAP River Rapid Development Environment plug-in',),
('SAP Road Map Explorer',),
('SAP Rounds Manager',),
('SAP S/4HANA',),
('SAP S/4HANA business partner',),
('SAP S/4HANA Cloud',),
('SAP S/4HANA Cloud ABAP Environment',),
('SAP S/4HANA Cloud Data Migration',),
('SAP S/4HANA Cloud Extensibility',),
('SAP S/4HANA Cloud for Asset Management',),
('SAP S/4HANA Cloud for central procurement',),
('SAP S/4HANA Cloud for enterprise portfolio and project management',),
('SAP S/4HANA Cloud for Finance',),
('SAP S/4HANA Cloud for Human Resources',),
('SAP S/4HANA Cloud for intelligent product selection',),
('SAP S/4HANA Cloud for Manufacturing',),
('SAP S/4HANA Cloud for Professional Services',),
('SAP S/4HANA Cloud for projects',),
('SAP S/4HANA Cloud for projects, project collaboration',),
('SAP S/4HANA Cloud for Research and Development',),
('SAP S/4HANA Cloud for Sales',),
('SAP S/4HANA Cloud for Service',),
('SAP S/4HANA Cloud for Sourcing and Procurement',),
('SAP S/4HANA Cloud for Supply Chain',),
('SAP S/4HANA Cloud front end',),
('SAP S/4HANA Cloud integration with SAP Cloud for Customer',),
('SAP S/4HANA Cloud Localization',),
('SAP S/4HANA Cloud Logistics for Brazil',),
('SAP S/4HANA Cloud Master Data',),
('SAP S/4HANA Cloud, extended edition',),
('SAP S/4HANA Cloud, test data refresh',),
('SAP S/4HANA Embedded Analytics',),
('SAP S/4HANA Finance',),
('SAP S/4HANA Finance for group reporting',),
('SAP S/4HANA for advanced ATP',),
('SAP S/4HANA for central procurement, integration with SAP S/4HANA',),
('SAP S/4HANA for Enterprise Contract Management',),
('SAP S/4HANA for product compliance',),
('SAP S/4HANA integration with SAP Concur solutions',),
('SAP S/4HANA Logistics for Brazil',),
('SAP S/4HANA migration cockpit',),
('SAP S/4HANA Supply Chain for extended service parts planning',),
('SAP Sales Analysis for Retail',),
('SAP Sales Analysis for Retail, edition for SAP HANA',),
('SAP Sales Cloud',),
('SAP Sales Manager',),
('SAP Sales Order Notification',),
('SAP Sanctioned-Party List',),
('SAP Sapphire',),
('SAP Screen Personas',),
('SAP Select',),
('SAP Service and Asset Manager',),
('SAP Service Cloud',),
('SAP Service Virtualization by Micro Focus',),
('SAP Signature Management by DocuSign, add-on for SAP Customer Experience solutions',),
('SAP Signavio',),
('SAP Signavio Journey Modeler',),
('SAP Signavio Process Collaboration Hub',),
('SAP Signavio Process Governance',),
('SAP Signavio Process Governance Collaborator',),
('SAP Signavio Process Insights',),
('SAP Signavio Process Intelligence',),
('SAP Signavio Process Manager',),
('SAP Signavio Value Accelerators',),
('SAP Single Sign-On',),
('SAP Smart Business',),
('SAP Smart Business, service discovery',),
('SAP Solution Manager',),
('SAP Sourcing and SAP Contract Lifecycle Management',),
('SAP Spend Performance Management',),
('SAP SQL Anywhere',),
('SAP SRM, add-on for bid security and expert bid evaluation',),
('SAP Strategic Sourcing Suite',),
('SAP Strategy Management',),
('SAP Student Lifecycle Management',),
('SAP Subscription Billing',),
('SAP SuccessFactors Compensation',),
('SAP SuccessFactors Document Management Core by Open Text',),
('SAP SuccessFactors Employee Central',),
('SAP SuccessFactors Employee Central - Employee Profile',),
('SAP SuccessFactors Employee Central Global Benefits',),
('SAP SuccessFactors Employee Central integration to SAP Business Suite',),
('SAP SuccessFactors Employee Central Payroll',),
('SAP SuccessFactors Employee Central Payroll, third-party data integration tool',),
('SAP SuccessFactors Employee Central Service Center',),
('SAP SuccessFactors Extended Enterprise Content Management by OpenText',),
('SAP SuccessFactors HXM Core',),
('SAP SuccessFactors HXM Suite',),
('SAP SuccessFactors Learning',),
('SAP SuccessFactors Learning Marketplace',),
('SAP SuccessFactors Mobile',),
('SAP SuccessFactors Onboarding',),
('SAP SuccessFactors Onboarding 1.0',),
('SAP SuccessFactors Opportunity Marketplace',),
('SAP SuccessFactors People Analytics',),
('SAP SuccessFactors People Central Hub',),
('SAP SuccessFactors Performance &amp; Goals',),
('SAP SuccessFactors platform',),
('SAP SuccessFactors Recruiting',),
('SAP SuccessFactors Recruiting Posting',),
('SAP SuccessFactors Succession &amp; Development',),
('SAP SuccessFactors Time Tracking',),
('SAP SuccessFactors Visa and Permits Management',),
('SAP SuccessFactors Work Zone',),
('SAP SuccessFactors Work-Life',),
('SAP SuccessFactors Workforce Analytics',),
('SAP SuccessFactors Workforce Planning',),
('SAP Summit',),
('SAP Supplier Lifecycle Management',),
('SAP Supplier Relationship Management',),
('SAP Supplier Relationship Management for SAP ERP',),
('SAP Supply Chain Control Tower',),
('SAP Supply Chain Management',),
('SAP Supply Chain Performance Management',),
('SAP Supply Network Collaboration',),
('SAP Sustainability Performance Management',),
('SAP Sybase Mainframe Connect',),
('SAP Talent Visualization by Nakisa',),
('SAP Task Center',),
('SAP Tax Classification and Reporting',),
('SAP Tax Compliance',),
('SAP Tax Declaration Framework for Brazil',),
('SAP Tax Intelligence and Management by All Tax, IRPJ/CSLL module',),
('SAP Tax Intelligence and Management by All Tax, TRABALHIST module',),
('SAP Teamcenter by Siemens',),
('SAP TechEd',),
('SAP Territory and Quota',),
('SAP Test Acceleration and Optimization',),
('SAP Test Data Migration Server',),
('SAP Text Analysis',),
('SAP Timesheet',),
('SAP Transformation Navigator',),
('SAP Translation Hub',),
('SAP Transportation Management',),
('SAP Travel Expense Approval',),
('SAP Travel Expense Report',),
('SAP Travel Receipt Capture',),
('SAP Treasury and Risk Management',),
('SAP Treasury and Risk Management, version for the United States',),
('SAP Universal ID',),
('SAP University Alliances',),
('SAP Utilities Customer Engagement',),
('SAP Utility Customer E-Services',),
('SAP Variant Configuration and Pricing',),
('SAP Visual Business',),
('SAP Vora',),
('SAP Waste and Recycling',),
('SAP Watch List Screening',),
('SAP Web Analytics (pilot)',),
('SAP Web Application Server for SAP S/4HANA',),
('SAP Web Channel Experience Management',),
('SAP Web IDE',),
('SAP Web IDE, hybrid app toolkit add-on',),
('SAP Web IDE, personal edition',),
('SAP Women in Tech',),
('SAP Work Manager',),
('SAP Workflow Management',),
('SAP Workflow Management, business rules capability',),
('SAP Workflow Management, process visibility capability',),
('SAP Workflow Management, workflow capability',),
('SAP Workforce Management',),
('SAP Workforce Performance Builder, desktop edition',),
('SAP Workforce Performance Builder, enterprise edition',),
('SAP Workforce Performance Builder, manager option',),
('SAP Workforce Performance Builder, producer option',),
('SAP Young Thinkers',),
('SAPUI5',),
('SCM APO Demand Planning (FCS)',),
('SCM APO Global ATP',),
('SCM APO Integration (CIF)',),
('SCM APO Master Data (MD)',),
('SCM APO Production Planning and Detailed Scheduling (PP/DS)',),
('SCM APO SAP LiveCache',),
('SCM APO Service Parts Planning',),
('SCM APO Supply Network Planning (SNP)',),
('SCM BCS Business Consolidation',),
('SCM Optimization',),
('SD (Sales and Distribution)',),
('SD Billing',),
('SD Sales',),
('search and classification engine (TREX) for SAP CRM',),
('Security',),
('Serverless Computing',),
('service development SDK for SAP BTP',),
('Service Ticket Intelligence',),
('Settlement Management',),
('Situation Handling',),
('Software Logistics',),
('Software Logistics - Change Control and Transport',),
('Software Logistics - Front-End Installation',),
('Software Logistics - Lifecycle Management Automation',),
('Software Logistics - System Maintenance',),
('Software Logistics - System Provisioning',),
('software logistics toolset',),
('SOLMAN Business Process Operations',),
('SOLMAN Change Control Management',),
('SOLMAN Custom Code Management',),
('SOLMAN Data Volume Management',),
('SOLMAN Diagnostics',),
('SOLMAN IT Service Management',),
('SOLMAN Process Management',),
('SOLMAN Project Management',),
('SOLMAN SAP Engagement and Service Delivery',),
('SOLMAN Setup/Configuration/LMDB',),
('SOLMAN System Monitoring',),
('SOLMAN Test Suite',),
('Sourcing and Procurement - Purchase Contract Management',),
('Sports and Entertainment',),
('SQL',),
('SRM Account Assignment',),
('SRM Bidding',),
('SRM Catalog Management',),
('SRM Confirmation',),
('SRM Contracts',),
('SRM External Requirements',),
('SRM Live Auction',),
('SRM Middleware',),
('SRM Organization and Business Partner Assignment',),
('SRM Performance, Upgrade, Security, Install',),
('SRM Personalized Object Worklist',),
('SRM Printing and Attachments',),
('SRM Purchase Order',),
('SRM Shopping Cart',),
('SRM Sourcing Cockpit',),
('SRM Supplier Self-Service',),
('SRM UI',),
('SRM Workflow',),
('SuccessConnect',),
('Support Services',),
('SUSE Linux Enterprise Server',),
('Sustainability',),
('Talent Management',),
('Telecommunications',),
('test automation tool for SAP S/4HANA Cloud',),
('the intercompany integration solution for SAP Business One',),
('Training',),
('Travel and Transportation',),
('Treasury Management',),
('UI Business Server Pages (BSP)',),
('UI data protection logging for SAP S/4HANA',),
('UI data protection masking for SAP S/4HANA',),
('UI Floorplan Manager for Web Dynpro ABAP',),
('UI SAP Business Client (NWBC)',),
('UI SAP GUI for Java',),
('UI SAP GUI for Windows',),
('UI theme designer',),
('UI Web Dynpro ABAP',),
('UI Web Dynpro Java',),
('UI WebGUI and Internet Transaction Server (ITS)',),
('User Experience',),
('User Interface',),
('Utilities',),
('Virtualization',),
('Wholesale Distribution',),
('Windows Server',),
('WorkConnect by SAP',),

('SAP Process Mining by Celonis, cloud edition',),
		('SAP HANA, version for IBM Power Systems architecture',),
		('MM Service Procurement',),
		('Windows Server',),
		('SAP Leonardo IoT Bridge',),
		('SAP Agile Data Preparation, on-premise edition',),
		('SAP Data Intelligence Cloud',),
		('SAP Business Information Warehouse',),
		('SAP REACH Compliance',),
		('SAP Product Stewardship Network',),
		('SAP Ariba Supply Chain',),
		('SAP Fiori Client for Android',),
		('SAP Lumira Cloud',),
		('SAP Ariba Supply Chain for iOS',),
		('SAP Liquidity Management for Banking',),
		('SAP StreamWork',),
		('lifecycle management for SAP BusinessObjects Enterprise',),
		('SAP Fiori Client for iOS',),
		('SAP Transportation Management integration with SAP Convergent Invoicing',),
		('SAP Quality Center by Micro Focus, enterprise edition',),
		('SAP Solution Manager, enterprise edition',),
		('SAP Gateway for Microsoft',),
		('SAP Business Planning and Consolidation',),
		('SAP Streaming Analytics',),
		('Update and Maintain Software',),
		('JAVA Development',),
		('integration add-on for SAP ERP HCM and SAP SuccessFactors HXM Suite',),
		('SAP Workforce Performance Builder, navigator option',),
		('Database and Data Management',),
		('Data Intelligence',),
		('SAP Sales Cloud, imaging intelligence add-on',),
		('Sybase Adaptive Server Enterprise',),

		('SAP BusinessObjects - Desktop Intelligence (DeskI)',),
		('BI rapid-configuration package for SAP HANA',),
		('SAP Digital Asset Management by OpenText',),
		('Experience Management',),
		('SAP Supply Chain Info Center',),
		('SAP CRM Sales for Windows',),
		('landscape verification for SAP Solution Manager',),
		('service parts management',),
		('accelerated application delivery for SAP NetWeaver',),
		('Focused Build and Focused Insights for SAP Solution Manager',),
		('SAP SQL Anywhere, cloud edition',),
		('SAP Vehicles Network',),

		('service taxation enhancements for Brazil',),
		('SAP One Domain Model',),
		('SAP Business One, version for Asia Pacific Japan',),
		('SAP HANA, enterprise extended edition',),
		('SAP Master Data Governance, enterprise asset management extension by Utopia',),
		('mobile app builder add-on for SAP Mobile Platform, consumer edition',),
		('manager self-services add-on',),
		('Crystal Enterprise',),
		('SAP Predictive Maintenance and Service, cloud edition',),
		('SAP HANA Live for Insurance',),
		('SAP Fiori app implementation foundation',),
		('SAP HANA Live for Manufacturing',),
		('UI add-on for SAP Supplier Relationship Management',),
		('SAP Knowledge Acceleration, version for cross-application time sheet',),
		('SAP Cloud for Financials',),
		('SAP HANA Live for SAP Business Suite foundation component',),
		('SAP Forecasting and Replenishment (for use with SAP merchandising software)',),
		('conversion, migration, and analysis tools',),
		('SAP Student Activity Hub',),
		('SAP Revenue Accounting and Reporting, integration with sales and distribution',),
		('SAP Fiori for SAP Fashion Management',),
		('SAP EHS Management, Web interface add-on',),
		('SAP Workplaces for Insurance',),
		('SAP Hybris as a Service on SAP Cloud Platform',),
		('SAP GRC Access Approver for Android',),
		('UI SAP GUI for Windows',),
		('SAP Configure, Price, and Quote',),
		('SAP enhancement package for SAP SCM, version for SAP HANA',),
		('Business Transformation',),
		('SAP Fan Experience',),
		('SAP HANA Live for SAP GTS',),
		('SAP Consumer Insight 365',),
		('SAP Authenticator for Android',),
		('PowerBuilder',),
		('SAP Management of Change',),
		('SAP Yard Logistics',),
		('SAP EHS Regulatory Content global package',),
		('SAP HANA data warehousing foundation',),
		('SAP Data Quality Management SDK',),
		('SAP Digital Interconnect',),
		('SAP Knowledge Acceleration for SAP Business Planning and Consolidation',),
		('SAP HANA remote data sync',),
		('SAP BusinessObjects - Legacy',),
		('SAP Document Compliance',),
		('SAP Customer Business Planning',),
		('SAP Localization Hub, tax service',),
		('Measure Software Performance',),
		('SAP Anywhere',),
		('SAP Cloud Platform Big Data Services 1711',),
		('Dell Boomi AtomSphere',),
		('SAP Event Ticketing, cloud edition',),
		('SAP CX Enablement Portal',),
		('SAP Business ByDesign studio',),
		('Migrate Data',),
		('SAP Solution Manager, version for SAP HANA',),
		('SAP Supply Chain Management, add-on for transportation management',),
		('SAP Environmental Compliance',),
		('SAP Forum',),
		('Create Project Roadmap',),
		('SAP NetWeaver Application Server for ABAP, OEM version',),
		('portal development kit for Microsoft .NET',),
		('SAP Asset Lifecycle Accounting',),
		('SAP Hybris Billing',),
		('SAP Advanced Track and Trace for Pharmaceuticals',),
		('Get Software Support',),
		('SAP Master Data Governance, retail and fashion management extension by Utopia',),
		('integration option for Microsoft Office SharePoint software',),
		('SAP Master Data Management Extension',),
		('Collect User Feedback',),
		('SAP Fiori apps for travel management in SAP ERP',),
		('SAP Sales and Operations Planning',),
		('SAP Productivity Composer by ANCILE',),
		('User Interface',),
		('project \'Kyma\'',),
		('HCM Benefits',),
		('SAP Contact Center, cloud edition',),
		('SAP Process Mining by Celonis',),
		('SAP Business One SDK',),
		('SAP Solution Manager adapter for SAP Quality Center by HPE',),
		('SAP Networked Logistics Hub',),

		('SAP Secondary Distribution for Oil & Gas',),
		('FIN Financial Supply Chain Management',),
		('SAP HANA, Internet of Things edition',),
		('SAP Quality Center by HPE, service test module',),
		('SAP Fiori Mentor',),
		('SAP Enable Now, consumption option',),
		('SAP Connected Goods',),
		('migration solution for SAP Business ByDesign feature pack',),
		('UI Web Dynpro Java',),
		('Implement Software',),
		('SAP Mobile Secure, partner edition',),
		('EWM - Work Order Processing',),
		('SAP Customer Retention',),
		('SAP Hybris Cloud for Customer mobile app',),
		('SAP NetWeaver Mobile',),
		('asset management for oil and gas',),
		('SAP Leonardo',),
		('Wholesale Distribution',),
		('SAP Commerce integration with SAP CRM',),
		('SAP Product Content Hub',),
		('SAP Insurance Analyzer',),
		('SAP Advanced Data Migration by BackOffice Associates',),
		('SAP Quality Center by Micro Focus, premier edition',),
		('SAP Agricultural Contract Management',),
		('SAP S/4HANA embedded analytics',),
		('SAP Vehicle Insights',),
		('Small and Midsize Enterprises',),
		('SAP Enterprise App Modeler',),
		('SAP Fiori for SAP Master Data Governance',),
		('SAP S/4HANA Supply Chain for secondary distribution',),
		('SAP Content to Go',),
		('UI WebGUI and Internet Transaction Server (ITS)',),
		('SAP Sales Cloud, starter edition',),
		('SAP Inventory Manager for Maximo',),
		('SAP HANA Live for SAP S/4HANA Finance',),
		('UI SAP GUI for Java',),
		('SAP Hybris Merchandising',),
		('SAP Extension Suite',),
		('SAP 3D Visual Enterprise Viewer',),
		('SAP Best Practices',),
		('SAP Business Banking',),
		('SQL Anywhere',),
		('maintenance planner',),
		('SAP Business Network Supplier',),
		('SAP Upscale Commerce',),
		('SAP Roambi',),
		('SBOP SDK',),
		('SAP Information Steward Accelerator by Syniti',),
		('SAP Knowledge Workspace',),
		('SAP Authenticator for iOS',),
		('SAP Data Services, language option for text data processing SDK, OEM edition',),
		('SAP Medical Research Insights',),
		('SAP LoadRunner by Micro Focus, performance center edition',),
		('SAP Fiori for SAP HANA Live for SAP ERP',),
		('SAP Concur Fusion',),
		('SAP HANA Live for SAP PLM',),
		('SAP Business One integration for SAP NetWeaver',),
		('HCM Travel Management',),
		('business process blueprint',),
		('SAP Cloud Platform Process Visibility',),
		('SAP Cloud for Travel and Expense',),
		('Business Objects Performance Management',),
		('UI WebClient UI Framework',),
		('Intel Distribution for Apache Hadoop for SAP Software',),
		('SAP IoT services for SAP BTP',),
		('SAP enhancement package for SAP CRM, version for SAP HANA',),
		('SAP Commerce Cloud, on-premise download',),
		('advanced simulation for supply network planning',),
		('SAP Notes Management',),
		('SAP Trade Management',),
		('SAP Supplier Problem-Solving',),
		('Internet of Things (IoT)',),
		('UI Web Dynpro ABAP',),
		('SAP HANA geospatial content',),
		('SAP Business ByDesign, subsidiaries edition',),
		('SAP Accelerated Trade Promotion Planning',),
		('SAP HANA Live for SAP solutions for GRC 10.1',),

		('SAP Process Control, starter kit for financial reporting',),
		('SAP Supplier Relationship Management, add-on for procurement planning',),
		('SAP Hybris Marketing, loyalty option',),
		('Syclo Agentry analytics',),
		('SAP HANA Live for SAP CRM',),
		('Conduct Testing',),
		('SAP Product Configuration, on-premise edition',),
		('SAP Event Insight',),
		('capital investment planning',),
		('mobile service for SAP Fiori',),
		('SAP Master Data Services, on-premise edition',),
		('SAP Fiori for SAP Extended Warehouse Management',),
		('SAP Crystal Presentation Design',),
		('SAP AR Warehouse Picker',),
		('SAP Customer Insight for iPad',),
		('Provide User Support',),
		('SAP Multiresource Scheduling with optimizer',),
		('SAP Leonardo Machine Learning Foundation',),
		('SAP S/4HANA migration object modeler',),
		('SAP Landscape Management, standard edition',),
		('SAP Fiori Cloud demo',),
		('SAP Product Configuration',),
		('SAP Plant Maintenance Rapid Mart',),
		('SAP Analytics Cloud connectors',),

		('commerce reporting add-on for SAP Mobile Platform, consumer edition',),
		('Evaluate Software Capabilities and Services',),
		('SAP RealSpend mobile app',),
		('SAP Material Availability',),
		('gateway to SAP NetWeaver Mobile',),
		('SAP POS Services',),
		('Duet',),
		('SAP IoT services for SAP BTP, Cloud Foundry environment',),
		('SAP Brand Impact',),
		('Create Business Case',),
		('FIN Overhead Cost',),
		('SAP Disclosure Management, XBRL reporting add-ons',),
		('SAP Hybris Knowledge Central by MindTouch',),
		('SAP Extended Warehouse Management for Fashion',),
		('SAP Customer Activity Repository applications bundle',),
		('SAP Fiori for SAP S/4HANA Finance',),
		('SAP 3D Visual Enterprise Author',),
		('SAP Workforce Scheduling and Optimization by ClickSoftware',),
		('SAP Edge Services, on-premise edition',),
		('SAP Distributed Manufacturing',),
		('SAP Build Classic',),
		('SAP Roambi Analytics for iOS',),
		('SAP HANA Live tools',),
		('SAP Fiori for SAP Event Management',),
		('Coffee Corner',),
		('SAP BusinessObjects Financial Consolidation starter kit for IFRS',),
		('SAP Master Data Services, cloud edition',),
		('SAP Business ByDesign mobile',),
		('Business Objects Intelligence Manager',),
		('mobile applications on project \'Gateway\'',),
		('SAP Fiori for SAP Solution Manager',),
		('SAP Business ByDesign, add-on for agile project management',),
		('SAP Predictive Maintenance and Service, technical foundation',),
		('SAP Knowledge Acceleration, version for SAP BusinessObjects Web Intelligence',),
		('SAP Sales and Operations Planning (SAP SOP)',),
		('SAP Fiori for SAP EHS Management',),
		('SAP EHS Regulatory Content package for the Americas',),
		('SAP Cloud Platform Extension Factory',),
		('data cleansing package for SAP BusinessObjects BI, Edge edition, version with data management',),
		('SAP Incentive Administration by Vistex and SAP Paybacks and Chargebacks by Vistex',),
		('SAP IoT Application Enablement',),
		('SAP R/3 Enterprise',),
		('SAP HANA Cloud Services',),
		('SAP Predictive Analysis',),
		('SAP BusinessObjects Business Intelligence, Edge edition, standard package',),
		('SAP Smart Business, core data services version',),
		('SAP Customer Analytics for Retail',),
		('SAP Fraud Watch',),
		('SAP for Utilities, customer care and service component',),
		('multiresource scheduling',),
		('SAP Knowledge Acceleration, version for SAP Lumira',),
		('SAP HANA Live for Retail',),
		('SAP Connected Parking',),
		('SAP Predictive Maintenance and Service',),
		('SAP Cash Forecasting',),
		('Virtualization',),
		('component extension for SAP Environment, Health, and Safety Management',),
		('SAP Tax Intelligence and Management by All Tax',),
		('SAP Enterprise Architecture Designer, edition for SAP HANA',),
		('mobile service for development and operations',),
		('Stay Compliant',),
		('SAP Ariba Planning Collaboration',),
		('SAP BusinessObjects Quality Management for Healthcare',),
		('SAP Cloud Platform',),
		('SAP Bank Communication Management, option for multisystem payment consolidation',),
		('UI theme designer',),
		('SAP Content Server)',),
]

with con:
    con.executemany(sql, tagdata)






